"""added payroll table

Revision ID: fe3fcd22455b
Revises: 8c296b86890d
Create Date: 2024-08-07 16:25:28.482232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3fcd22455b'
down_revision = '8c296b86890d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.String(length=30), nullable=False),
    sa.Column('bonus', sa.String(length=30), nullable=True),
    sa.Column('deductions', sa.String(length=30), nullable=True),
    sa.Column('paydate', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('payroll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll')
    # ### end Alembic commands ###
